spring:
  application:
    name: user-service
  profiles:
    active: @env@  # 动态激活环境
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  # 全局时间格式
    time-zone: GMT+8
    serialization:
      indent-output: true  # 美化输出
      write-dates-as-timestamps: false  # 日期不转为时间戳
# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.yy.user.entity
  type-handlers-package: com.yy.user.config.mybatis.handler.common
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启 SQL 日志
    map-underscore-to-camel-case: true  # 自动驼峰转换（如 user_name → userName）
