# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    nacos:
      discovery:
        enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.2.75:5433/pg-test?sslmode=disable
    username: postgres
    password: dsk806888!@#
server:
  port: 8000

seata:
  enabled: false


