# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    nacos:
      discovery:
        enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.2.75:5433/pg-test?sslmode=disable
    username: postgres
    password: dsk806888!@#
server:
  port: 8000

seata:
  enabled: false

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.yy.user.entity
  type-handlers-package: com.yy.user.config.mybatis.handler.common
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启 SQL 日志
    map-underscore-to-camel-case: true  # 自动驼峰转换（如 user_name → userName）
  global-config:
    db-config:
      id-type: auto  # 主键自增策略（需 PostgreSQL 配置序列）
      logic-delete-field: deleted  # 逻辑删除字段
      logic-not-delete-value: 0
      logic-delete-value: 1

